app = "hoedu-solution"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  NODE_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1