services:
  # Dịch vụ Web Service cho ứng dụng Node.js
  - type: web
    name: hoedu-solution
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hoedu-db
          property: connectionString

databases:
  # PostgreSQL database
  - name: hoedu-db
    plan: free